require 'spec_helper'

describe 'collectd::plugin::hddtemp', type: :class do
  let :facts do
    {
      osfamily: 'RedHat',
      collectd_version: '4.8.0'
    }
  end

  context ':ensure => present' do
    let :facts do
      {
        osfamily: 'RedHat',
        collectd_version: '5.5'
      }
    end

    let :params do
      { port: 6666 }
    end
    it 'Will create /etc/collectd.d/10-hddtemp.conf' do
      should contain_file('hddtemp.load').with(ensure: 'present',
                                               path: '/etc/collectd.d/10-hddtemp.conf',
                                               content: "#\ Generated by Puppet\n<LoadPlugin hddtemp>\n  Globals false\n</LoadPlugin>\n\n<Plugin \"hddtemp\">\n  Host \"127.0.0.1\"\n  Port 6666\n</Plugin>\n\n")
    end
  end

  context ':ensure => absent' do
    let :params do
      { ensure: 'absent' }
    end
    it 'Will not create /etc/collectd.d/10-hddtemp.conf' do
      should contain_file('hddtemp.load').with(ensure: 'absent',
                                               path: '/etc/collectd.d/10-hddtemp.conf')
    end
  end

  context ':port is not an integer' do
    let :params do
      { port: 'port' }
    end
    it 'Will raise an error about :port not being an integer' do
      should compile.and_raise_error(%r{Expected first argument to be an Integer or Array, got String})
    end
  end
end
