require 'spec_helper'

describe 'collectd::plugin::network', :type => :class do

  context ':ensure => present, default params' do
    let :facts do
      {:osfamily => 'RedHat'}
    end
    it 'Will create /etc/collectd.d/10-network.conf' do
      should contain_file('network.load').with({
        :ensure  => 'present',
        :path    => '/etc/collectd.d/10-network.conf',
        :content => /\#\ Generated by Puppet\nLoadPlugin network\n\n<Plugin network>\n  \n<\/Plugin>\n/,
      })
    end
  end


end