# frozen_string_literal: true

require 'spec_helper'

describe 'collectd::plugin::fscache' do
  on_supported_os.each do |os, os_facts|
    context "on #{os}" do
      let(:facts) { os_facts }

      context ':ensure => present' do
        it 'Will create 10-fscache.conf' do
          is_expected.to contain_file('fscache.load').with(
            ensure: 'present',
            content: %r{\#\ Generated by Puppet\n<LoadPlugin fscache>\n}
          )
        end
      end

      context ':ensure => absent' do
        let(:params) { { ensure: 'absent' } }

        it 'Will not create 10-fscache.conf' do
          is_expected.to contain_file('fscache.load').with_ensure('absent')
        end
      end
    end
  end
end
