require 'spec_helper'

describe 'collectd::plugin::curl', :type => :class do

  context ':ensure => present, simple params' do
    let :facts do
      {:osfamily => 'RedHat'}
    end
    let :params do
      {
        :pages => {
          'test' => {
            'url'     => 'http://www.example.com/query',
            'matches' => [{'regex' => 'SPAM \\(Score: (-?[0-9]+\\.[0-9]+)\\)', 'dstype' => 'CounterAdd', 'type' => 'counter'}],
          }
        }
      }
    end
    it 'Will create /etc/collectd.d/curl-test.conf with pages configuration' do
      should contain_file('/etc/collectd.d/curl-test.conf').with({
        :ensure  => 'present',
        :content => "<Plugin curl>\n  <Page \"test\">\n    URL \"http://www.example.com/query\"\n  <Match>\n    Regex \"SPAM \\(Score: (-?[0-9]+\\.[0-9]+)\\)\"\n    DSType \"CounterAdd\"\n    Type \"counter\"\n  </Match>\n\n  </Page>\n</Plugin>\n",
      })
    end
    it 'it will create /etc/collectd.d/10-curl.conf to load the plugin' do  
      should contain_file('curl.load').with({
        :ensure  => 'present',
        :content => /\#\ Generated by Puppet\nLoadPlugin curl\n\n/,
      })
    end
  end
end

