require 'spec_helper'

describe 'collectd::plugin::network', :type => :class do

  context ':ensure => present, default params' do
    let :facts do
      {:osfamily => 'RedHat'}
    end
    it 'Will create /etc/collectd.d/10-network.conf' do
      should contain_file('network.load').with({
        :ensure  => 'present',
        :path    => '/etc/collectd.d/10-network.conf',
        :content => /\#\ Generated by Puppet\nLoadPlugin network\n\n<Plugin network>\n<\/Plugin>\n/,
      })
    end
  end

  context ':ensure => present, specific params, collectd version 4.6' do
    let :facts do
      { :osfamily         => 'Redhat',
        :collectd_version => '4.6'
      }
    end
    let :params do
      { :listeners => { 'mylistener' => { 'port' => '1234' }}
      }
    end

    it 'Will create /etc/collectd.d/10-network.conf for collectd < 4.7' do
      should contain_file('network.load').with({
        :ensure  => 'present',
        :path    => '/etc/collectd.d/10-network.conf',
        :content => "# Generated by Puppet\nLoadPlugin network\n\n<Plugin network>\n  Listen \"mylistener\" \"1234\"\n</Plugin>\n",
      })
    end
  end

  context ':ensure => present, specific params, collectd version 5.1.0' do
    let :facts do
      { :osfamily         => 'Redhat',
        :collectd_version => '5.1.0'
      }
    end
    let :params do
      { :listeners => { 'mylistener' => { 'port' => '1234' }}
      }
    end

    it 'Will create /etc/collectd.d/10-network.conf for collectd >= 4.7' do
      should contain_file('network.load').with({
        :ensure  => 'present',
        :path    => '/etc/collectd.d/10-network.conf',
        :content => "# Generated by Puppet\nLoadPlugin network\n\n<Plugin network>\n  <Listen \"mylistener\" \"1234\">\n\n  </Listen>\n</Plugin>\n",
      })
    end
  end

  context ':ensure => present, create 2 simple servers, collectd 4.6' do
    let :facts do
      { :osfamily         => 'Redhat',
        :collectd_version => '4.6',
      }
    end
    let :params do
      { :servers => { 
          'node1' => { 'port' => '1234' },
          'node2' => { 'port' => '4321' }
        }
      }
    end

    it 'Will create /etc/collectd.d/10-network.conf for collectd <= 4.6' do
      should contain_file('network.load').with({
        :ensure  => 'present',
        :path    => '/etc/collectd.d/10-network.conf',
        :content => "# Generated by Puppet\nLoadPlugin network\n\n<Plugin network>\n  Server \"node1\" \"1234\"\n  Server \"node2\" \"4321\"\n</Plugin>\n",
      })
    end
  end

  context ':ensure => present, create 2 simple servers, collectd 5.1' do
    let :facts do
      { :osfamily         => 'Redhat',
        :collectd_version => '5.1.0',
      }
    end
    let :params do
      { :servers => {
          'node1' => { 'port' => '1234' },
          'node2' => { 'port' => '4321' }
        }
      }
    end

    it 'Will create /etc/collectd.d/10-network.conf for collectd >= 4.7' do
      should contain_file('network.load').with({
        :ensure  => 'present',
        :path    => '/etc/collectd.d/10-network.conf',
        :content => "# Generated by Puppet\nLoadPlugin network\n\n<Plugin network>\n  <Server \"node1\" \"1234\">\n\n  </Server>\n  <Server \"node2\" \"4321\">\n\n  </Server>\n</Plugin>\n",
      })
    end
  end

  context ':ensure => present, create 2 servers with one complex, collectd 5.1.0' do
    let :facts do
      { :osfamily         => 'Redhat',
        :collectd_version => '5.1.0',
      }
    end
    let :params do
      { :servers => {
          'node1' => { 
            'port'      => '1234',
            'interface' => 'eth0',
            'securitylevel' => 'Encrypt',
            'username'      => 'foo',
            'password'      => 'bar',
           },
          'node2' => { 'port' => '4321' }
        }
      }
    end

    it 'Will create /etc/collectd.d/10-network.conf for collectd >= 4.7' do
      should contain_file('network.load').with({
        :ensure  => 'present',
        :path    => '/etc/collectd.d/10-network.conf',
        :content => "# Generated by Puppet\nLoadPlugin network\n\n<Plugin network>\n  <Server \"node1\" \"1234\">\n    SecurityLevel \"Encrypt\"\n    Username \"foo\"\n    Password \"bar\"\n    Interface \"eth0\"\n\n  </Server>\n  <Server \"node2\" \"4321\">\n\n  </Server>\n</Plugin>\n",
      })
    end
  end


  context ':ensure => present, create 2 listeners with one complex, collectd 5.1.0' do
    let :facts do
      { :osfamily         => 'Redhat',
        :collectd_version => '5.1.0',
      }
    end
    let :params do
      { :listeners => {
          'node1' => {
            'port'          => '1234',
            'interface'     => 'eth0',
            'securitylevel' => 'Encrypt',
            'authfile'      => '/dev/null',
           },
          'node2' => { 'port' => '4321' }
        }
      }
    end

    it 'Will create /etc/collectd.d/10-network.conf for collectd >= 4.7' do
      should contain_file('network.load').with({
        :ensure  => 'present',
        :path    => '/etc/collectd.d/10-network.conf',
        :content => "# Generated by Puppet\nLoadPlugin network\n\n<Plugin network>\n  <Listen \"node1\" \"1234\">\n    SecurityLevel \"Encrypt\"\n    AuthFile \"/dev/null\"\n    Interface \"eth0\"\n\n  </Listen>\n  <Listen \"node2\" \"4321\">\n\n  </Listen>\n</Plugin>\n",
      })
    end
  end

  context ':ensure => absent' do
    let :facts do
      {:osfamily => 'RedHat'}
    end
    let :params do
      {:ensure => 'absent'}
    end

    it 'Will not create /etc/collectd.d/10-network.conf' do
      should contain_file('network.load').with({
        :ensure => 'absent',
        :path   => '/etc/collectd.d/10-network.conf',
      })
    end
  end
end

