require 'spec_helper'

describe 'collectd::plugin::uuid', type: :class do
  let :facts do
    {
      osfamily: 'RedHat',
      collectd_version: '4.8.0'
    }
  end

  context ':ensure => present' do
    let :facts do
      {
        osfamily: 'RedHat',
        collectd_version: '5.5'
      }
    end

    let :params do
      { ensure: 'present' }
    end
    it 'Will create /etc/collectd.d/10-uuid.conf' do
      should contain_file('uuid.load').with(ensure: 'present',
                                            path: '/etc/collectd.d/10-uuid.conf',
                                            content: "#\ Generated by Puppet\n<LoadPlugin uuid>\n  Globals false\n</LoadPlugin>\n\n<Plugin \"uuid\">\n  UUIDFile \"/etc/uuid\"\n</Plugin>\n\n")
    end
  end

  context ':ensure => absent' do
    let :params do
      { ensure: 'absent' }
    end
    it 'Will not create /etc/collectd.d/10-uuid.conf' do
      should contain_file('uuid.load').with(ensure: 'absent',
                                            path: '/etc/collectd.d/10-uuid.conf')
    end
  end
end
