require 'spec_helper'

describe 'collectd::plugin::network::server', :type => :define do

  context ':ensure => present, default params, collectd version 4.6' do
    let(:title) { 'myserver' }
    let :facts do
      { :osfamily         => 'Redhat',
        :collectd_version => '4.6'
      }
    end

    it 'Will create /etc/collectd.d/network-server-myserver.conf for collectd < 4.7' do
      should contain_file('network-server-myserver.conf').with({
        :ensure  => 'present',
        :path    => '/etc/collectd.d/network-server-myserver.conf',
        :content => "# Generated by Puppet\n<Plugin network>\n  Server \"myserver\" \"25826\"\n</Plugin>\n",
      })
    end
  end

  context ':ensure => present, default params, collectd version 5.1.0' do
    let(:title) { 'myserver' }
    let :facts do
      { :osfamily         => 'Redhat',
        :collectd_version => '5.1.0'
      }
    end

    it 'Will create /etc/collectd.d/network-server-myserver.conf for collectd >= 4.7' do
      should contain_file('network-server-myserver.conf').with({
        :ensure  => 'present',
        :path    => '/etc/collectd.d/network-server-myserver.conf',
        :content => "# Generated by Puppet\n<Plugin network>\n  <Server \"myserver\" \"25826\">\n    SecurityLevel \"None\"\n  </Server>\n</Plugin>\n",
      })
    end
  end

  context ':ensure => present, testing all custom params' do
    let(:title) { 'myserver' }
    let :facts do
      { :osfamily         => 'Redhat',
        :collectd_version => '5.1.0'
      }
    end
    let :params do
      { :server        => 'myserver',
        :port          => '42',
        :interface     => 'eth1',
        :securitylevel => 'Encrypt',
        :username      => 'username',
        :password      => 'password',
      }
    end

    it 'Will create /etc/collectd.d/network-server-myserver.conf for collectd >= 4.7' do
      should contain_file('network-server-myserver.conf').with({
        :ensure  => 'present',
        :path    => '/etc/collectd.d/network-server-myserver.conf',
        :content => "# Generated by Puppet\n<Plugin network>\n  <Server \"myserver\" \"42\">\n    SecurityLevel \"Encrypt\"\n    Username \"username\"\n    Password \"password\"\n    Interface \"eth1\"\n  </Server>\n</Plugin>\n",
      })
    end
  end

end
