require 'spec_helper'

describe 'collectd::plugin::network::listen', :type => :define do

  context ':ensure => present, default params, collectd version 4.6' do
    let(:title) { 'myserver' }
    let :facts do
      { :osfamily         => 'Redhat',
        :collectd_version => '4.6'
      }
    end

    it 'Will create /etc/collectd.d/network-listen-myserver.conf for collectd < 4.7' do
      should contain_file('network-listen-myserver.conf').with({
        :ensure  => 'present',
        :path    => '/etc/collectd.d/network-listen-myserver.conf',
        :content => "# Generated by Puppet\n<Plugin network>\n  Listen \"myserver\" \"25826\"\n</Plugin>\n",
      })
    end
  end

  context ':ensure => present, default params, collectd version 5.1.0' do
    let(:title) { 'myserver' }
    let :facts do
      { :osfamily         => 'Redhat',
        :collectd_version => '5.1.0'
      }
    end

    it 'Will create /etc/collectd.d/network-listen-myserver.conf for collectd >= 4.7' do
      should contain_file('network-listen-myserver.conf').with({
        :ensure  => 'present',
        :path    => '/etc/collectd.d/network-listen-myserver.conf',
        :content => "# Generated by Puppet\n<Plugin network>\n  <Listen \"myserver\" \"25826\">\n    SecurityLevel \"None\"\n  </Listen>\n</Plugin>\n",
      })
    end
  end

  context ':ensure => present, testing all custom params' do
    let(:title) { 'myserver' }
    let :facts do
      { :osfamily         => 'Redhat',
        :collectd_version => '5.1.0'
      }
    end
    let :params do
      { :authfile      => '/tmp/nope',
        :port          => '42',
        :interface     => 'eth1',
        :securitylevel => 'Encrypt',
      }
    end

    it 'Will create /etc/collectd.d/network-listen-myserver.conf for collectd >= 4.7' do
      should contain_file('network-listen-myserver.conf').with({
        :ensure  => 'present',
        :path    => '/etc/collectd.d/network-listen-myserver.conf',
        :content => "# Generated by Puppet\n<Plugin network>\n  <Listen \"myserver\" \"42\">\n    SecurityLevel \"Encrypt\"\n    AuthFile \"/tmp/nope\"\n    Interface \"eth1\"\n  </Listen>\n</Plugin>\n",
      })
    end
  end

end
